# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O2BQOHUfMjV0zYoFs0aM2CjEqaAV-FDP
"""

import pandas as pd

file_path = '/content/sample_data/countries_of_the_world.csv'
df = pd.read_csv(file_path)

all_countries = df['Country'].tolist()

df['Population'] = pd.to_numeric(df['Population'], errors='coerce')
countries_over_10_million = df[df['Population'] > 10000000]['Country'].tolist()

df['Area (sq. mi.)'] = pd.to_numeric(df['Area (sq. mi.)'], errors='coerce')
ukraine_area = df[df['Country'].str.contains('Ukraine', case=False, na=False)]['Area (sq. mi.)'].values[0]
large_countries = df[(df['Population'] > 10000000) & (df['Area (sq. mi.)'] > ukraine_area)]['Country'].tolist()

df['Service'] = pd.to_numeric(df['Service'], errors='coerce')
top_10_services = df.nlargest(10, 'Service')['Country'].tolist()

sea_bordering_countries = df[df['Coastline (coast/area ratio)'] > 0]['Country'].tolist()

results = {
    "Всі країни": all_countries,
    "Країни з населенням понад 10 млн": countries_over_10_million,
    "Країни з населенням понад 10 млн та площа більше ніж в Україні": large_countries,
    "Топ 10 країн у сфері послуг": top_10_services,
    "Країни, які межують з морем": sea_bordering_countries
}

for key, value in results.items():
    print(f"{key}:\n{value}\n")